baseurl = "https://vort3x.me/"
languageCode = "en-us"
title = "VorT3x's Blog"
theme = "cactus"
googleAnalytics = "UA-62813262-1"
disqusShortname = "VorT3x"

[permalinks]
  post = "/:filename/"

[params]
  name = "Dmitri Logvinenko"
  description = "Thoughts, stories and ideas"
  bio = "Blogger - Programmer - Gopher"
  twitter = "VorT3x"
  enableRSS = true
  aboutAuthor = "Software developer who's passionate about writing code and learning new technologies. Currently concentrated on Go. Professionally works as Technical Lead."
  copyright = "© Copyright 2015-16 Dmitri Logvinenko"
